### ISSUE TITLE
触摸板是不是MSFT0001 Hot patch？

### ISSUE THREAD

**Issue by gpdeepblue** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#1]
如果是，不妨参考一下这位朋友的实现
[YOGA-S740](https://github.com/frozenzero123/YOGA-S740)

**Comment by ThrRip** [comment]
你好！

感谢关注 ThrRip 的 OpenCore 开源项目。

针对您对触摸板驱动实现的建议，我做出了一些探究，但是发现，他的方法并不适用于 Lenovo Yoga C740，因为 Lenovo Yoga C740 与 S740 之间存在很大的差异，触摸板也一样。

Hot Patch 的方法我也曾尝试过，但以失败告终，目前使用 Clover 引导的 macOS Catalina 10.15.7 配合 VoodooPS2Controller、VoodooI2C 和 VoodooI2CHID 可以实现触控板和触控屏的使用，但是触控屏会在睡眠并唤醒后失效，所以暂时无解。

ThrRip 也将继续更新研究进度。感谢您的支持！

**Comment by MJYINMC** [comment]
同型号（但我是10710U的），同样的问题，hotpatch的方法对同款CPU的小新有用，查阅到comet lake CPU使用VoodooI2C失败的另外一种可能问题，不妨一起试验一下。
https://www.notion.so/Using-VoodooI2C-on-comet-lake-cpu-e-g-i5-10210u-142930887087445eaa533120455da5dc

**Comment by ThrRip** [comment]
我已收到您的建议！

我会在有时间的时候尝试按照您提供的方法修复触控版和触控屏，请继续关注此项目，以跟随我的进度。

如果您觉得此项目帮助到了您，请点亮 Star，感谢您的支持！

**Comment by ThrRip** [comment]
首先，感谢大家对 ThrRip 的 OpenCore EFI 开源项目的支持。

对于 OpenCore-EFI-Laptop-Lenovo-YOGA-C740-14IML 的触摸板驱动问题，相信大家都花费了很多心血来解决。

目前， @MJYINMC 转载了一种理论上可行的方法在本 Issue 的第三个内容中，但是我在进行实践时，发现编译过程会发生很多错误，并且无法找到解决方法。

下面是当前遇到的错误的截图：

![Stuck When I'm Building VoodooI2C](https://user-images.githubusercontent.com/54434330/101903336-14602580-3bef-11eb-9ce2-a0dd7c9a07d5.png)

ThrRip 将一直持续研究此方法和编译过程中的错误，除非证明了此方法不可行。如果您有好的解决方法，欢迎向 thrrip@thrrip.space 发送邮件，或者直接将您的方法写在此 Issue 中。

如果您觉得此项目帮助到了您，请点亮 Star 并考虑 Follow 我。

再次感谢大家的支持！

**Comment by yzhEric** [comment]
大佬或许可以参考一下FydeOS？
虽然跟MacOS差别好像有点大
但是目前的版本测试下来，触控板和触摸屏都能正常驱动
——来自小白的小小建议

**Comment by ThrRip** [comment]
您好！

此 Issue 已经被关闭，并且对触摸板的研究已经实现了我们的目标。

目前触摸板能够完美驱动并支持手势，触控屏在部分用户的设备上能正常使用，但是 ThrRip 的 Lenovo Yoga C740-14IML 的触控屏并没有正常驱动。

如果您觉得有更好的方法来驱动触控屏，请建立新的 Issue，我将在第一时间回复。

注：目前无法更新到 macOS Big Sur 11.0.1 的问题，有用户提出和触控屏未被屏蔽有关，但未得到证实。

ThrRip 敬上
