### ISSUE TITLE
求助，

### ISSUE THREAD

**Issue by pscly** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#10]
开机的时候出现这个，然后进不去系统![IMG_20210307_121603.jpg](https://user-images.githubusercontent.com/41666995/110228800-fdf00e80-7f3e-11eb-9efc-242651d3401e.jpg)

**Comment by ThrRip** [comment]
请按照顺序依次尝试：
1. 尝试按任意键，是否能进入启动界面；
2. 启用引导参数 `-v`，看看是否能发现错误；
3. 重装系统。

我遇到的时候，按照提示说的「请按一下按键，或等几秒钟以继续启动」，无论是「按一下按键」还是「等几秒钟」都可以正常启动。

**Comment by pscly** [comment]
进入系统之后 进度条加载一半的时候就会自动重启， 
(我不知道如何启用引导参数 -v  求助)

**Comment by ThrRip** [comment]
启用 `-v` 参数的方法，我在本项目 #6 提到过。

**Comment by pscly** [comment]
![Screenshot_20210307_191126_com.android.keyguard.jpg](https://user-images.githubusercontent.com/41666995/110237806-f9e0e280-7f78-11eb-80f2-376e3e133ea7.jpg)

这个是什么的问题啊

**Comment by ThrRip** [comment]
你得看上面啊，下面人家都告诉你内核错误，正在导出日志了。

然后我再重申一遍，本项目的 Issue 不是 Hackintosh 求助区。
