### ISSUE TITLE
谢谢付出，efi很好用

### ISSUE THREAD

**Issue by oreoft** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#11]
但是开启触摸屏以后会有一点耗电的增加，以后问一下后续还会修复更新efi吗。感谢你做出的努力，谢谢

**Comment by ThrRip** [comment]
EFI 还是会更新的，只是可能慢一点，因为最近比较忙。

你说的“开启触摸屏”是指在睡眠并唤醒以后，触摸屏能正常使用，但是耗电增加吗？

**Comment by oreoft** [comment]
> EFI 还是会更新的，只是可能慢一点，因为最近比较忙。
> 
> 你说的“开启触摸屏”是指在睡眠并唤醒以后，触摸屏能正常使用，但是耗电增加吗？
