### ISSUE TITLE
作者您好，我安装遇到问题想请教一下，exitbs:start

### ISSUE THREAD

**Issue by oreoft** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#12]
报错是卡eb
提示 [EB|#LOG:EXITBS:START]，因为图片很大就不配了。您有什么好的解决思路嘛

另外我想问一下，c740可以关闭cfg吗，为什么您的efizhe'liang'g这两个勾没有勾选。是因为这个原因吗，我勾上以后其实也不行
![image](https://user-images.githubusercontent.com/51789848/119849793-8202d280-bf3f-11eb-839e-e6d12d9fc983.png)

**Comment by ThrRip** [comment]
您好，感谢您关注 ThrRip 的开源项目！

针对您的问题，其实您做出的探索已经完全足够了。

由于这款设备的特殊性，解决方法我在本项目的 [README.md 的 Problem still exist 部分](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#problems-still-exist)的第六项提到了，如有需要的话可以参考。

**Comment by oreoft** [comment]
> 您好，感谢您关注 ThrRip 的开源项目！
> 
> 针对您的问题，其实您做出的探索已经完全足够了。
> 
> 由于这款设备的特殊性，解决方法我在本项目的 [README.md 的 Problem still exist 部分](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#problems-still-exist)的第六项提到了，如有需要的话可以参考。

谢谢你的回复，我在描述的清楚一点哈
我是安装10.15出现这个[EB|#LOG:EXITBS:START](还没格盘，进安装界面都进不去)
我已经在config把cfg两项已经勾选了，bios没有解锁cfg理应勾选这两项也能进行安装界面

最后....您提取的c740的bios偏移量都分享出来吗，bios都是一样的反复造轮子就不太好了，我想使用grub-mod-setup_var修改偏移量

**Comment by cca2878** [comment]
> > 您好，感谢您关注 ThrRip 的开源项目！
> > 针对您的问题，其实您做出的探索已经完全足够了。
> > 由于这款设备的特殊性，解决方法我在本项目的 [README.md 的 Problem still exist 部分](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#problems-still-exist)的第六项提到了，如有需要的话可以参考。
> 
> 谢谢你的回复，我在描述的清楚一点哈
> 我是安装10.15出现这个[EB|#LOG:EXITBS:START](%E8%BF%98%E6%B2%A1%E6%A0%BC%E7%9B%98%EF%BC%8C%E8%BF%9B%E5%AE%89%E8%A3%85%E7%95%8C%E9%9D%A2%E9%83%BD%E8%BF%9B%E4%B8%8D%E5%8E%BB)
> 我已经在config把cfg两项已经勾选了，bios没有解锁cfg理应勾选这两项也能进行安装界面
> 
> 最后....您提取的c740的bios偏移量都分享出来吗，bios都是一样的反复造轮子就不太好了，我想使用grub-mod-setup_var修改偏移量

cfg与缓冲区大小的BIOS修改，我自己有写过一篇博客，有一部分关于这个内容。
https://blog.fscircle.com/2021/03/166.html
希望能有些帮助。

**Comment by oreoft** [comment]
> > > 您好，感谢您关注 ThrRip 的开源项目！
> > > 针对您的问题，其实您做出的探索已经完全足够了。
> > > 由于这款设备的特殊性，解决方法我在本项目的 [README.md 的 Problem still exist 部分](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#problems-still-exist)的第六项提到了，如有需要的话可以参考。
> > 
> > 
> > 谢谢你的回复，我在描述的清楚一点哈
> > 我是安装10.15出现这个[EB|#LOG:EXITBS:START](%E8%BF%98%E6%B2%A1%E6%A0%BC%E7%9B%98%EF%BC%8C%E8%BF%9B%E5%AE%89%E8%A3%85%E7%95%8C%E9%9D%A2%E9%83%BD%E8%BF%9B%E4%B8%8D%E5%8E%BB)
> > 我已经在config把cfg两项已经勾选了，bios没有解锁cfg理应勾选这两项也能进行安装界面
> > 最后....您提取的c740的bios偏移量都分享出来吗，bios都是一样的反复造轮子就不太好了，我想使用grub-mod-setup_var修改偏移量
> 
> cfg与缓冲区大小的BIOS修改，我自己有写过一篇博客，有一部分关于这个内容。
> https://blog.fscircle.com/2021/03/166.html
> 希望能有些帮助。

好的，谢谢，我还是比较喜欢使用IFR文件然后使用https://github.com/datasone/grub-mod-setup_var  这个工具去修改，可以更加高效安全的修改更多offset

**Comment by ThrRip** [comment]
偏移量的话因为我也是好久以前修改的 BIOS，现在完全忘记了，而且这款机器很神奇，不同型号、不同国家版本的 BIOS 信息可能都不一样，所以您可能还是需要自己用我提到的文章内的方法自己查验一下。

> 请在动手前检查自己的 BIOS 是否为联想官网提供的最新版本，如果不是，请下载并更新。有些时候只是更新 BIOS 也有可能可以解决问题。

**Comment by oreoft** [comment]
> 偏移量的话因为我也是好久以前修改的 BIOS，现在完全忘记了，而且这款机器很神奇，不同型号、不同国家版本的 BIOS 信息可能都不一样，所以您可能还是需要自己用我提到的文章内的方法自己查验一下。
> 
> > 请在动手前检查自己的 BIOS 是否为联想官网提供的最新版本，如果不是，请下载并更新。有些时候只是更新 BIOS 也有可能可以解决问题。

好的，我以为您备份了IFR文件，那我自己去提取一下吧，但是我也很疑惑为什么我在config勾选这两项依然会卡EB.理应如果是cfg问题应该解决了，会不会我还有其他设置问题

**Comment by ThrRip** [comment]
的确不应该在经过如您所说设置以后依然出现问题，那也就只剩下最后一种情况了：
- **镜像损坏**

相信您知道如何解决。

**Comment by oreoft** [comment]
> 的确不应该在经过如您所说设置以后依然出现问题，那也就只剩下最后一种情况了：
> 
> * **镜像损坏**
> 
> 相信您知道如何解决。

好的非常感谢，我自己再倒腾倒腾，感谢ThrRip的工作~

**Comment by oreoft** [comment]
> > 的确不应该在经过如您所说设置以后依然出现问题，那也就只剩下最后一种情况了：
> > 
> > * **镜像损坏**
> > 
> > 相信您知道如何解决。
> 
> 好的非常感谢，我自己再倒腾倒腾，感谢ThrRip的工作~

我解锁了cfg，然后更换了硬盘，然后重新制作了镜像，但是然后这样报错，bios上除了把安全启动关闭，还需要调整什么吗，好奇怪，为什么会这样，我是安装10.15
![image](https://user-images.githubusercontent.com/51789848/120016473-3cb1d400-c017-11eb-8a5a-ec7f86de291f.png)

**Comment by ThrRip** [comment]
根据图中的 `OC: Prelinked injection AirportItwm.kext () - Invalid Parameter`，你可能需要暂时将 `AirportItlwm.kext` 从 `/EFI/OC/Kexts` 中移除，并在 `config.plist` 中删除相关的部分，在系统安装完成后再加入。

**Comment by oreoft** [comment]
> 根据图中的 `OC: Prelinked injection AirportItwm.kext () - Invalid Parameter`，你可能需要暂时将 `AirportItlwm.kext` 从 `/EFI/OC/Kexts` 中移除，并在 `config.plist` 中删除相关的部分，在系统安装完成后再加入。

我昨天也试过了，但是依然不行，提示如下
![image](https://user-images.githubusercontent.com/51789848/120053654-fe8bd300-c05d-11eb-9a58-cdefa2c7659f.png)

**Comment by oreoft** [comment]
c

> 根据图中的 `OC: Prelinked injection AirportItwm.kext () - Invalid Parameter`，你可能需要暂时将 `AirportItlwm.kext` 从 `/EFI/OC/Kexts` 中移除，并在 `config.plist` 中删除相关的部分，在系统安装完成后再加入。

这个AirportItwm报错应该是我安装的版本是10.5，而驱动版本是11. 我已经排除了这个驱动依然不行。
至此我尝试了如下尝试
1. bios关闭Secure Boot和Intel SGX
2. 提取bios，然后将SaSetup中100行07列格中的值改为02，设置DVMT为64M；将CpuSetup中30行0E列的值改为00，解锁CFG Lock。
3. 打开OpenCore的配置文件config.plist，勾选如下三个选项：AppleCpuPmCfgLock， AppleXcpmCfgLock，IgnoreInvalidFlexRatio
4. 更换硬盘
5. 更换引导介质

依然EB|#LOG:EXITBS:START

**Comment by ThrRip** [comment]
按照 [Laptop Coffee Lake Plus and Comet Lake | OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html) 中的说法，
![image](https://user-images.githubusercontent.com/54434330/120057439-9b0d9f80-c075-11eb-8b78-da2e210dde21.png)
如果 CFG Lock（MSR 0xE2）已经关闭，则 `AppleCpuPmCfgLock` 和 `AppleXcpmCfgLock` 都不应该开启；如果 MSR 寄存器（MSR 0x194）已经关闭，则 `IgnoreInvalidFlexRatio` 不应该开启。在我使用的 `config.plist` 中，以上三项都没有开启。所以您说的第三项尝试可能需要重新进行。

**Comment by oreoft** [comment]
> 按照 [Laptop Coffee Lake Plus and Comet Lake | OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html) 中的说法，
> ![image](https://user-images.githubusercontent.com/54434330/120057439-9b0d9f80-c075-11eb-8b78-da2e210dde21.png)
> 如果 CFG Lock（MSR 0xE2）已经关闭，则 `AppleCpuPmCfgLock` 和 `AppleXcpmCfgLock` 都不应该开启；如果 MSR 寄存器（MSR 0x194）已经关闭，则 `IgnoreInvalidFlexRatio` 不应该开启。在我使用的 `config.plist` 中，以上三项都没有开启。所以您说的第三项尝试可能需要重新进行。

各个排列组合都试过了，就是因为没改您cofig不行以后，才探索多种可能方式

**Comment by oreoft** [comment]
> > 按照 [Laptop Coffee Lake Plus and Comet Lake | OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html) 中的说法，
> > ![image](https://user-images.githubusercontent.com/54434330/120057439-9b0d9f80-c075-11eb-8b78-da2e210dde21.png)
> > 如果 CFG Lock（MSR 0xE2）已经关闭，则 `AppleCpuPmCfgLock` 和 `AppleXcpmCfgLock` 都不应该开启；如果 MSR 寄存器（MSR 0x194）已经关闭，则 `IgnoreInvalidFlexRatio` 不应该开启。在我使用的 `config.plist` 中，以上三项都没有开启。所以您说的第三项尝试可能需要重新进行。
> 
> 各个排列组合都试过了，就是因为没改您cofig不行以后，才探索多种可能方式

我今天都更新了一下bios，还是不行，怎么搞都是卡这个eb

**Comment by oreoft** [comment]
> 按照 [Laptop Coffee Lake Plus and Comet Lake | OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html) 中的说法，
> ![image](https://user-images.githubusercontent.com/54434330/120057439-9b0d9f80-c075-11eb-8b78-da2e210dde21.png)
> 如果 CFG Lock（MSR 0xE2）已经关闭，则 `AppleCpuPmCfgLock` 和 `AppleXcpmCfgLock` 都不应该开启；如果 MSR 寄存器（MSR 0x194）已经关闭，则 `IgnoreInvalidFlexRatio` 不应该开启。在我使用的 `config.plist` 中，以上三项都没有开启。所以您说的第三项尝试可能需要重新进行。

有没有可能是我安装10.15的原因，我现在安装一下big sur试试

**Comment by oreoft** [comment]
> > 按照 [Laptop Coffee Lake Plus and Comet Lake | OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html) 中的说法，
> > ![image](https://user-images.githubusercontent.com/54434330/120057439-9b0d9f80-c075-11eb-8b78-da2e210dde21.png)
> > 如果 CFG Lock（MSR 0xE2）已经关闭，则 `AppleCpuPmCfgLock` 和 `AppleXcpmCfgLock` 都不应该开启；如果 MSR 寄存器（MSR 0x194）已经关闭，则 `IgnoreInvalidFlexRatio` 不应该开启。在我使用的 `config.plist` 中，以上三项都没有开启。所以您说的第三项尝试可能需要重新进行。
> 
> 有没有可能是我安装10.15的原因，我现在安装一下big sur试试

bigsur 也不行.....

**Comment by oreoft** [comment]
> > > 您好，感谢您关注 ThrRip 的开源项目！
> > > 针对您的问题，其实您做出的探索已经完全足够了。
> > > 由于这款设备的特殊性，解决方法我在本项目的 [README.md 的 Problem still exist 部分](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#problems-still-exist)的第六项提到了，如有需要的话可以参考。
> > 
> > 
> > 谢谢你的回复，我在描述的清楚一点哈
> > 我是安装10.15出现这个[EB|#LOG:EXITBS:START](%E8%BF%98%E6%B2%A1%E6%A0%BC%E7%9B%98%EF%BC%8C%E8%BF%9B%E5%AE%89%E8%A3%85%E7%95%8C%E9%9D%A2%E9%83%BD%E8%BF%9B%E4%B8%8D%E5%8E%BB)
> > 我已经在config把cfg两项已经勾选了，bios没有解锁cfg理应勾选这两项也能进行安装界面
> > 最后....您提取的c740的bios偏移量都分享出来吗，bios都是一样的反复造轮子就不太好了，我想使用grub-mod-setup_var修改偏移量
> 
> cfg与缓冲区大小的BIOS修改，我自己有写过一篇博客，有一部分关于这个内容。
> https://blog.fscircle.com/2021/03/166.html
> 希望能有些帮助。

兄弟，你的bios只关闭Secure Boot和Intel SGX然后提取bios，然后将SaSetup中100行07列格中的值改为02，设置DVMT为64M；将CpuSetup中30行0E列的值改为00，解锁CFG Lock。使用efi就可以正常安装对吗，我也是这样操作的，但是折腾好久，结果事与愿违

**Comment by oreoft** [comment]
> > > 按照 [Laptop Coffee Lake Plus and Comet Lake | OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake-plus.html) 中的说法，
> > > ![image](https://user-images.githubusercontent.com/54434330/120057439-9b0d9f80-c075-11eb-8b78-da2e210dde21.png)
> > > 如果 CFG Lock（MSR 0xE2）已经关闭，则 `AppleCpuPmCfgLock` 和 `AppleXcpmCfgLock` 都不应该开启；如果 MSR 寄存器（MSR 0x194）已经关闭，则 `IgnoreInvalidFlexRatio` 不应该开启。在我使用的 `config.plist` 中，以上三项都没有开启。所以您说的第三项尝试可能需要重新进行。
> > 
> > 
> > 有没有可能是我安装10.15的原因，我现在安装一下big sur试试
> 
> bigsur 也不行.....

我找到问题了，我的cpu是i7导致的问题，我已经解决了，麻烦了，耽误这么长时间，很不好意思。

**Comment by oreoft** [comment]
> > > > 您好，感谢您关注 ThrRip 的开源项目！
> > > > 针对您的问题，其实您做出的探索已经完全足够了。
> > > > 由于这款设备的特殊性，解决方法我在本项目的 [README.md 的 Problem still exist 部分](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#problems-still-exist)的第六项提到了，如有需要的话可以参考。
> > > 
> > > 
> > > 谢谢你的回复，我在描述的清楚一点哈
> > > 我是安装10.15出现这个[EB|#LOG:EXITBS:START](%E8%BF%98%E6%B2%A1%E6%A0%BC%E7%9B%98%EF%BC%8C%E8%BF%9B%E5%AE%89%E8%A3%85%E7%95%8C%E9%9D%A2%E9%83%BD%E8%BF%9B%E4%B8%8D%E5%8E%BB)
> > > 我已经在config把cfg两项已经勾选了，bios没有解锁cfg理应勾选这两项也能进行安装界面
> > > 最后....您提取的c740的bios偏移量都分享出来吗，bios都是一样的反复造轮子就不太好了，我想使用grub-mod-setup_var修改偏移量
> > 
> > 
> > cfg与缓冲区大小的BIOS修改，我自己有写过一篇博客，有一部分关于这个内容。
> > https://blog.fscircle.com/2021/03/166.html
> > 希望能有些帮助。
> 
> 兄弟，你的bios只关闭Secure Boot和Intel SGX然后提取bios，然后将SaSetup中100行07列格中的值改为02，设置DVMT为64M；将CpuSetup中30行0E列的值改为00，解锁CFG Lock。使用efi就可以正常安装对吗，我也是这样操作的，但是折腾好久，结果事与愿违

问题解决了，谢谢你小兄弟，你很热心
