### ISSUE TITLE
1.3.1遇到休眠问题，100%的电量合盖然后一晚上次日过来电量就是0需要充电才能开机

### ISSUE THREAD

**Issue by oreoft** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#13]
closed

**Comment by oreoft** [comment]
@ThrRip 查询到唤醒原因，大概从18:27开始休眠的电量是100%，刚刚七点唤醒发现睡死了，然后强制重启开机发现掉了10%的电
![image](https://user-images.githubusercontent.com/51789848/120635612-41570c00-c49f-11eb-8446-de79802ea25c.png)

**Comment by ThrRip** [comment]
稍等一下，我20:05 100%电量合盖睡眠，等到21:05我看一下还剩多少。

**Comment by oreoft** [comment]
> 稍等一下，我20:05 100%电量合盖睡眠，等到21:05我看一下还剩多少。

好的，我查看日志，发现有很多异常唤醒。我40%电量昨晚九点开始合盖，一直唤醒，一直唤醒，到十点左右被唤醒的彻底没电
![image](https://user-images.githubusercontent.com/51789848/120729750-836d6580-c512-11eb-9cae-572fbfaece15.png)，希望对您有帮助，看看能不能解决我的问题。

**Comment by oreoft** [comment]
> 稍等一下，我20:05 100%电量合盖睡眠，等到21:05我看一下还剩多少。

不好意思， 点错了把这个关闭了，但是您测试的结果出来了吗
