### ISSUE TITLE
> 稍等一下，我20:05 100%电量合盖睡眠，等到21:05我看一下还剩多少。

### ISSUE THREAD

**Issue by oreoft** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#14]
> 稍等一下，我20:05 100%电量合盖睡眠，等到21:05我看一下还剩多少。

不好意思， 点错了把这个关闭了，但是您测试的结果出来了吗

_Originally posted by @oreoft in https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/issues/13#issuecomment-854652274_

**Comment by oreoft** [comment]
因为平时下班回家是断电的，电脑放公司，但是每次过来电脑就关机了。我看到我睡眠的时候有很多唤醒，经过查询资料，我加了一个sstd，log里面唤醒记录没有了，但是每小时耗电依然不变，大概一小时40%。我没辙了，感觉好难

**Comment by ThrRip** [comment]
抱歉哈，昨天把这事忘了，刚刚（20:02）开盖正常亮屏，电量还剩73%，也就是说睡眠24小时大概耗电27%。

**Comment by oreoft** [comment]
> 抱歉哈，昨天把这事忘了，刚刚（20:02）开盖正常亮屏，电量还剩73%，也就是说睡眠24小时大概耗电27%。

那好奇怪啊，睡眠24小掉27%我都可以接受。但是我现在1小时40%就太多了

**Comment by oreoft** [comment]
> > 抱歉哈，昨天把这事忘了，刚刚（20:02）开盖正常亮屏，电量还剩73%，也就是说睡眠24小时大概耗电27%。
> 
> 那好奇怪啊，睡眠24小掉27%我都可以接受。但是我现在1小时40%就太多了

我和您在描述一下，我是10710u，我参考https://github.com/daliansky/XiaoXinPro-13-hackintosh 已经仿冒cpuid ：0x0806EC、0x0806EB。然后我用的是ax201网卡，虽然我在主板已经屏蔽了

**Comment by ThrRip** [comment]
看起来你那个是因为 USB 的问题而被不断唤醒，你可能需要参照 [Why should you USB map | OpenCore Post-Install](https://dortania.github.io/OpenCore-Post-Install/usb) 来定制一下 USB，虽然我没有经过此操作也正常睡眠。

**Comment by oreoft** [comment]
> 看起来你那个是因为 USB 的问题而被不断唤醒，你可能需要参照 [Why should you USB map | OpenCore Post-Install](https://dortania.github.io/OpenCore-Post-Install/usb) 来定制一下 USB，虽然我没有经过此操作也正常睡眠。

可是我现在已经没有唤醒日志了。

**Comment by ThrRip** [comment]
但是之前有啊😂话说你加的是什么 SSDT？

**Comment by oreoft** [comment]
> 但是之前有啊😂话说你加的是什么 SSDT？

这是最骚的，之前有唤醒日志，我也怀疑是usb，并且大概率是怀疑网卡问题，因为我使用的是ax201。然后在网上找的了一个什么0补丁，打了一个ssdt。https://www.github.com/xxxzc/xps15-9550-macos/tree/master/ACPI%2FSSDT-GPRW.dsl。 然后这个日志就没了，不知道是真解决了还是假解决了，但是耗电依然存在

**Comment by ThrRip** [comment]
我用的也是 AX201，没有换网卡。
理论上来说，你的睡眠不断唤醒是因为 USB 或者电源状态在不断发生改变。这种情况引起的唤醒可以参考 [GPRW/UPRW/LANC Instant Wake Patch | OpenCore Post-Install](https://dortania.github.io/OpenCore-Post-Install/usb/misc/instant-wake.html)。切记，SSDT 不要乱加。
既然耗电依然存在，那就肯定是没有解决呀。
