### ISSUE TITLE
是否考虑支持macOS 12.0 Monterey？

### ISSUE THREAD

**Issue by qpc001** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#15]

**Comment by ThrRip** [comment]
如果 macOS 12 只是针对 WWDC21 所提到的 User space 内的部分功能进行了更改（例如 Universal Control、新的 Safari 等），那么肯定还是会继续支持下去。

但是支持的时间可能要等到 macOS 12 正式版释出了，因为这台电脑硬盘太小，没有足以建立第三个系统分区的空间，我也不想冒着风险升级到 macOS 12 Beta 版。

如果您升级到 macOS 12 Monterey 后发现 EFI 文件需要修改，欢迎通过 Pull Request 来支持此项目。
