### ISSUE TITLE
触控板控制鼠标不稳定

### ISSUE THREAD

**Issue by wang-zerui** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#16]
11.6系统，触控板控制鼠标会出现瞬移一小段的情况，不知道这个有办法搞定吗

**Comment by ThrRip** [comment]
你说的是使用触控板的时候，鼠标指针突然移动了一段不合理的距离？我没有遇到过，也无法想象是什么情况，建议先在 Windows 下测试是否有同样问题。

**Comment by wang-zerui** [comment]
似乎是插了鼠标导致的，拔掉鼠标后重启问题消失
