### ISSUE TITLE
DELETE THE ISSUES

### ISSUE THREAD

**Issue by Installer0001** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#17]
HEY, WOULD YOU PLEASE DELETE THE ISSUES HERE

https://github.com/ThrRip/OpenCore-EFI-Lenovo-B360-i5-8400/issues/2

I HAVE USED A DIFFERENT ACCOUNT ACCIDENTALLY INSTEAD OF PERSONAL ACCOUNT. I WOULD HIGHLY APPRECIATE IT IF YOU DELETE THEM.

**Comment by ThrRip** [comment]
Sorry, I'm not able to do it. The rules of the open-source community are always before your personal preference.

**Comment by Installer0001** [comment]
no no its not about personal preference, the account belongs to someone else and they didnt authorize me to post anything.

And your concern about public help, I'll post the same question again using this account and you can delete that previous comment.

Are you going to help me or not...

**Comment by ThrRip** [comment]
So is there any way you can prove that @AIOFrame is the account you have access to? If not, then I am deleting the issue created by others without any reason.

**Comment by Installer0001** [comment]
I asked from that account to delete the comments, and i requested from this account. Why would someone suddenly come and ask to replace comments?

And as i said please unarchive the repo and I'll ask same question from this account, you post the answer then you can delete the issues so this way you loose nothing.

**Comment by ThrRip** [comment]
OK, I unarchived that repo. Do what you need to do then.

**Comment by Installer0001** [comment]
Thank you very much, i have added the issue with this account. You can respond and please delete the issue created by AIO frame account.

And you can also delete this issue thread too. Thank you.
