### ISSUE TITLE
Stuck around IOG flags ... Generation from SMC report as ... IOPPF ...

### ISSUE THREAD

**Issue by cvltist** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#18]
As title says, during initial install the device hangs around IOG flags ... Generation from SMC report as ... IOPPF. Is there something I am missing? Thanks again for your write-up.

**Comment by ThrRip** [comment]
Are you trying to install macOS 11 Big Sur or macOS 12 Monterey?

**Comment by cvltist** [comment]
I am trying to install Monterey.

**Comment by ThrRip** [comment]
Do you have the latest BIOS flashed? If not, upgrade your BIOS and try again.

**Comment by cvltist** [comment]
Yes, it is the latest version. I noticed in your change history that you
previously had the same error. What kexts fixed the problem? I combed
through the config.plist and it looked good.

**Comment by pratus** [comment]
I am having the same issue

**Comment by ThrRip** [comment]
> Yes, it is the latest version. I noticed in your change history that you
> previously had the same error. What kexts fixed the problem? I combed
> through the config.plist and it looked good.

@cvltist In my opinion, you may try to recreate all SSDTs to fit your device. Here is a tutorial (use the "Manual" method, even prebuilt stuff are provided): _[Getting started with ACPI](https://dortania.github.io/Getting-Started-With-ACPI/)_.
