### ISSUE TITLE
thanks for your help！

### ISSUE THREAD

**Issue by bfsxzxh1** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#2]
I want to make a try. Should I install the Mac OS on the internal or external hard disk？

I would like to install the MAC on the external hard disk. Is it feasible？

**Comment by ThrRip** [comment]
It's feasible but I don't recommend that way.

Because the read/write speed is much slower on the external hard disk.

I prefer installing macOS on a SSD, and you will feel more comfortable when using macOS you installed.

**Comment by bfsxzxh1** [comment]
I'm going to divide disk d into 100g to install MacOS

Thank you for your EFI

**Comment by ThrRip** [comment]
OK, so could you give me a star and follow me? Thanks!
