### ISSUE TITLE
BaseSystem Freezes While Installing

### ISSUE THREAD

**Issue by prescott2m** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#20]
I Am Trying To Install macOS 12 (latest) on a C740 (i7 10510U, 512GB SSD, 16GB RAM) and it is freezing while installing.

Sometimes It Freezes At 12 minutes remaining, 13 minutes remaining, or 2 hours remaining. it's just unpredictable.
How do I get the latest version of macOS 12 Installed with no issues?

**Comment by ThrRip** [comment]
Hello there,

Do you mean the **Base System** (with a macOS installer window, version-based system logo, and a disk icon) freezes with a estimated remaining, or it freezes **after the _Base System stage_** (with a white Apple logo, and a progress bar, would reboot and enter this stage when finished works need to be done in the Base System)?

**Comment by prescott2m** [comment]
Freezes At The BaseSystem (with a macOS installer window, version-based system logo, and a disk icon) with time remaining.

**Comment by ThrRip** [comment]
You may need to set these quirks to `True` in `config.plist`:
- `NVRAM -> LegacyEnable`
- `NVRAM -> LegacyOverwrite`
- `NVRAM -> WriteFlash`

Save the config file, and on the next boot, choose **Reset NVRAM** in the OpenCore boot picker. After this, try to install the OS again.

Reference: [_Stuck at 2 minutes remaining - Userspace Issues | OpenCore Install Guide_](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/userspace-issues.html#stuck-at-2-minutes-remaining)

**Comment by prescott2m** [comment]
New problem: it freezes while formatting the drive as APFS.

**Comment by PolarWolf314** [comment]
Unfortunately, the only fix for freezing while formatting the drive as APFS is to get a new drive.

The Lenovo Yoga C740 has a Samsung PM981a inside it, which is completely incompatible with macOS even with the correct kexts. 

Have a look here for more information: https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html

**Comment by ThrRip** [comment]
> Unfortunately, the only fix for freezing while formatting the drive as APFS is to get a new drive.
> 
> The Lenovo Yoga C740 has a Samsung PM981a inside it, which is completely incompatible with macOS even with the correct kexts.
> 
> Have a look here for more information: https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html

That should be the correct answer. However, my machine came with a WD SN730 out of box, so I forgot this bit so bad😅

Anyways, thank you for pointing this out.
