### ISSUE TITLE
2.0.1版本的WIFI无法驱动

### ISSUE THREAD

**Issue by IMVector** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#22]
使用2.0.1替换上一个版本之后，无线网卡无法驱动了，WI-FI不能打开

**Comment by ThrRip** [comment]
请尝试重置 NVRAM（选择启动菜单中的 `Reset NVRAM` 选项）并**彻底删除**所有 `/EFI` 目录下的文件，再将确认无损坏的 `EFI` 文件夹放入 EFI 分区。
