### ISSUE TITLE
Not booting

### ISSUE THREAD

**Issue by agreek01** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#25]
Hi,
I have a C740 i7-10510U /16GB /UHD 630. I put this EFI folder into installation media and after few seconds it reboots. 
Is any way to edit and load this EFI to my laptop?
For 2 years now I am using 10.15 with 2 problems (build-in mic not working and wifi is not recognised) and now I am looking for Ventura upgrade. 
[opencore-2022-11-06-233803.txt](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/files/9950088/opencore-2022-11-06-233803.txt)
[opencore-2022-11-06-232727.txt](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/files/9950090/opencore-2022-11-06-232727.txt)

**Comment by ThrRip** [comment]
Hello there,

Thanks for your report. Unfortunately, you're having an i7 CPU which is different from the i5 I'm using and used to create these EFI files. Different CPU models may have different ACPI mapping and stuff, so you will have some work to do with it. However, there are users that reported a successful installation on the same system as yours. Don't lose hope ;)

As you're using Catalina 10.15, you should use the [`AirportItlwm.kext` for your OS version](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.1.0/AirportItlwm_v2.1.0_stable_Catalina.kext.zip). Installation instructions by [OpenIntelWireless](https://github.com/OpenIntelWireless) can be found here - [_Installation | OpenIntelWireless_](https://openintelwireless.github.io/itlwm/Installation.html#airportitlwm).

The problem with built-in microphones for this machine might not get solved - at least for a period. They are using Intel SST, [find more about it](https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html#miscellaneous).

Regards,
ThrRip

**Comment by agreek01** [comment]
Thank you so much!
