### ISSUE TITLE
4.0版本测试了一个月，基本稳定。

### ISSUE THREAD

**Issue by forgot64** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#26]
1.触摸偶尔失灵，不过无所谓。
2.暂时无法隔空，电脑可以发现手机，但点击无反应。ios系统16.7
3.我安装的14.1版本，由于无法更新，加了补丁添加一下启动项，提示更新14.5安装后无法进入系统。自己尝试用OCAT更新您的包，不论win端还是mac端均无法更新，网络没问题，但是一直无法从服务器download。
4.不知您还有后续15版本的开发计划么，谢谢。

**Comment by ThrRip** [comment]
> 触摸偶尔失灵，不过无所谓。

这是一个难以修复的已知问题。

> 暂时无法隔空，电脑可以发现手机，但点击无反应。ios系统16.7

这是 Intel 无线网卡相关的已知问题，详见 [Bluetooth Support | Wireless Buyers Guide](https://dortania.github.io/Wireless-Buyers-Guide/misc/bluetooth.html#so-why-does-bluetooth-work-on-my-intel-card)：
> > ... (usually with the loss of Handoff, AirDrop, etc).

和 [FAQ | OpenIntelWireless](https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#intelbtpatcher)：
> > Fixes for Continuity features and other issues are not planned.

> 我安装的14.1版本，由于无法更新，加了补丁添加一下启动项，提示更新14.5安装后无法进入系统。自己尝试用OCAT更新您的包，不论win端还是mac端均无法更新，网络没问题，但是一直无法从服务器download。

我不确定是否理解你的意思。你在尝试更新 OpenCore 还是 macOS，或两者都有？

> 不知您还有后续15版本的开发计划么

有，会在 macOS Sequoia 正式版发布后，且 OpenCore、Kexts 都基本支持 macOS Sequoia 时更新。
