### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by JellyAi** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#3]
![image](https://user-images.githubusercontent.com/9295828/102706612-63344c00-42ce-11eb-9ecd-ca46a1dc7c3e.jpg)
Hello I have stucked at install panel for about one hour, and do you know why? Please

**Comment by ThrRip** [comment]
Hello,

I've seen your picture.

I think it may be that your installation device is not stably connected to the computer. You can try to **force cancel and restart**, and then **install again**. I haven't had such a problem before.

And please star this project if it helps you. Thanks!

Regards,
ThrRip

**Comment by bfsxzxh1** [comment]
@ThrRip I have watched and star you,thanks

**Comment by ThrRip** [comment]
Hi,
Has that problem been solved?

**Comment by JellyAi** [comment]
Yet not. Let's try 10.15, I dont hone why

**Comment by ThrRip** [comment]
😂😂😂I think it should be possible to do so.
I was 10.15 at that time and then upgraded to 11.
You may also need to delete some things from EFI files, such as WiFi drivers, touchpad drivers, and many plugins of VirtualSMC.
Good Luck!

**Comment by JellyAi** [comment]
Hah, I tried 10.15, and It seems it does not work, the same symptom, I tried advices you list above, but it doesn't work. Thanks for your reply!

**Comment by ThrRip** [comment]
emmm...
So ... just do it yourself, I couldn't give you more advices. Thanks for your support!

**Comment by JellyAi** [comment]
Anyway thank you so much
