### ISSUE TITLE
兄弟机器 s740 问题求解

### ISSUE THREAD

**Issue by frozenzero123** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#5]
关于睡眠部分 你的能正常工作吗？ 还有就是你的ec0-off是为了什么？

**Comment by ThrRip** [comment]
您好！

感谢您关注 ThrRip 的开源项目！

首先，对于您的问题，您需要清楚的一点是，我们的设备型号不一样。我的是 [Lenovo Yoga C740-14IML](https://item.lenovo.com.cn/product/1007857.html)，您的是 [Lenovo Yoga S740](https://item.lenovo.com.cn/product/1009767.html)，这两者并不相同。

其次，我在使用我的 EFI 文件时，睡眠可以正常工作，并且唤醒后触摸屏就能正常使用了（如果不睡眠并唤醒，触摸屏无法使用）。

还有就是您对于 [SSDT-EC0_Off.aml](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/blob/main/EFI/OC/ACPI/SSDT-EC0_OFF.aml) 的问题，我已经在 [Commit ab36e0](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/commit/8427e8851b1b1275517033c9c2b683e3bf7a72af) 中说明，主要用于屏蔽设备自带的 EC（即 EC0）以避免出现某些问题。但我个人觉得并无必要，所以没有在 [config.plist](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/blob/main/EFI/OC/config.plist) 中开启它。

如果您觉得此项目帮助了您，可以给它一个 Star 吗？

**Comment by frozenzero123** [comment]
> 您好！
> 
> 感谢您关注 ThrRip 的开源项目！
> 
> 首先，对于您的问题，您需要清楚的一点是，我们的设备型号不一样。我的是 [Lenovo Yoga C740-14IML](https://item.lenovo.com.cn/product/1007857.html)，您的是 [Lenovo Yoga S740](https://item.lenovo.com.cn/product/1009767.html)，这两者并不相同。
> 
> 其次，我在使用我的 EFI 文件时，睡眠可以正常工作，并且唤醒后触摸屏就能正常使用了（如果不睡眠并唤醒，触摸屏无法使用）。
> 
> 还有就是您对于 [SSDT-EC0_Off.aml](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/blob/main/EFI/OC/ACPI/SSDT-EC0_OFF.aml) 的问题，我已经在 [Commit ab36e0](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/commit/8427e8851b1b1275517033c9c2b683e3bf7a72af) 中说明，主要用于屏蔽设备自带的 EC（即 EC0）以避免出现某些问题。但我个人觉得并无必要，所以没有在 [config.plist](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/blob/main/EFI/OC/config.plist) 中开启它。
> 
> 如果您觉得此项目帮助了您，可以给它一个 Star 吗？

ok！我是因为联想的睡眠 是aoac s0睡眠所以很好奇 你是如何成功睡眠的 ，因为我一直有睡眠方面的困惑，当然这个和我的显卡驱动并不完美有关！我在我机器没有找到任何修改s3睡眠的设定

**Comment by ThrRip** [comment]
很多情况下，Hackintosh 的睡眠问题都会和嵌入式控制器有关。

您可能需要参考 [Getting Started With ACPI](https://dortania.github.io/Getting-Started-With-ACPI) 来重新按照“手动方式”制作 SSDT-EC 和 SSDT-USBX 以修复睡眠问题。
