### ISSUE TITLE
启动时提示错误

### ISSUE THREAD

**Issue by bfsxzxh1** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#6]
![Screenshot_2021-01-10-17-39-41-673_com miui gallery](https://user-images.githubusercontent.com/75568672/104119536-e0e9f580-536a-11eb-9cd2-b562dd7111f3.jpg)

**Comment by bfsxzxh1** [comment]
Your computer restarted because of a problem. Press a key or wait
atew seconds to continue starting up.
Wore ordinateur a redemarre en raison d'un probleme. Pour poursuitre
Teredemarrage, appuyez surune touche ou patientezquelquessecondes.
E ordenador se ha reiniciado debido a un problema. Para continuar
conel arranque, pulse cualquier tecla o espere unos segundos.
thr Computer wurde aufgrund eines Problems neu gestartet. Drticken
Sie zum Fortfahren eine Taste oder warten Sie einige Sekunden.
問題於起老九大的了>匕1—夕老再起動L末L九。乙の未求起動才石場合脉
心于扎办の午一变押寸》、数秒間子の末末抬待古人龙合b。
电脑因出现问题而重新启动。请按一下按键，或等几秒钟以继续启动。

**Comment by ThrRip** [comment]
您好！

感谢您关注 ThrRip 的开源项目！

这项错误一般是由于上次启动 macOS 或是 macOS Base System 时强制关机引起的。我在遇到这个错误时，按照提示中的方法（“请按一下按键，或等几秒钟以继续启动。”）即可正常启动。

但是如果您多次遇到此问题，并且没有在启动 macOS 或 macOS Base System 时强制关机或断电，则您可能需要在 `config.plist -> NVRAM -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args` 中加入 `-v` `keepsyms=1` 和 `debug=0x100` 以查明导致此错误的原因。

> 让我感到奇怪的是，您上次在此项目提交 Issue 使用的是英文，但是这次您使用了中文。我想告诉您的是，在 ThrRip 的所有开源项目中提交 Issue 都可以使用中文或英文，不需要为语言问题而纠结。

如果您觉得此项目帮助了您，请点亮 Star。

**Comment by bfsxzxh1** [comment]
谢谢你的帮助 上次我看没有人使用中文提问 所以我就没好意思用中文
那我明天试试

**Comment by ThrRip** [comment]
好的😂，期待您的回复。

**Comment by bfsxzxh1** [comment]
我试了一下 不知道如何加入 -v keepsyms=1 和 debug=0x100 
我尝试了在子目录下创建 不行 
还是在哪里加入这两个参数 还得麻烦指导下

**Comment by bfsxzxh1** [comment]
我第一次尝试安装macos  不知道bios里面有啥需要注意的设置

**Comment by ThrRip** [comment]
`-v` `keepsyms=1` `debug=0x100` 三个参数需要在 `config.plist -> NVRAM -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args` 中加入。

BIOS 的设置可以参考 [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/)。

**Comment by bfsxzxh1** [comment]
![Screenshot_2021-01-13-06-18-06-782_com miui gallery](https://user-images.githubusercontent.com/75568672/104381323-3c80d280-5567-11eb-82c1-768b12d1e395.jpg)
启动时卡在这里了，有什么解决方案吗？

**Comment by ThrRip** [comment]
您可能需要将 `AirportItlwm.kext` 暂时从 `/EFI/OC/Kexts` 和 `config.plist` 中移除，再进行后续的尝试。

**Comment by bfsxzxh1** [comment]
![Screenshot_2021-01-13-22-16-03-532_com miui gallery](https://user-images.githubusercontent.com/75568672/104463631-f8381580-55ec-11eb-84a0-a56d70164514.jpg)
又卡在声卡了，😂

**Comment by ThrRip** [comment]
与此问题有关的事项，我在 [README.md](https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/blob/main/README.md) 中提到过：

> - ~~Stuck on `IOG flags ... Generation from SMC report as ... IOPPF ...`~~
  > Resolved after fixing SSDTs, adding some kernel extensions, etc.

在我自己配置我的 EFI 文件时，这个问题是如何解决的，现在我自己也记不太清了。但是看您的 `-v` 输出好像并非是 AppleALC 与声卡的问题，更可能的是和嵌入式控制器、IRQ 冲突等底层问题有关。

您可以自己尝试删除 `AppleALC.kext` 或使用其他方法来修复。

另外，因为 GitHub 是一个开源社区，使用 ThrRip 制作的 EFI 文件的开源社区成员不可能得到付费级别的服务。所以，此 Issue 将被关闭，您在安装过程中遇到的其他问题将不会再获得 ThrRip 的解答，因为这份 EFI 文件本身并没有任何问题。

感谢您对 ThrRip 的开源项目的支持！如果您觉得此项目帮助了您，请考虑点亮 Star。
