### ISSUE TITLE
谢谢你的帮助

### ISSUE THREAD

**Issue by bfsxzxh1** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#7]
能不能推荐个安装教程呢？
这个确实是麻烦的事，不好意思打扰了

**Comment by ThrRip** [comment]
如果需要安装教程的话，可以参考 OpenCore 的官方文档，但其中除了配置 OpenCore 以外还包含了更多关于 Hackintosh 的内容：
> [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide)

与其配套的还有：
> [Getting Started With ACPI](https://dortania.github.io/Getting-Started-With-ACPI/)
> [OpenCore Post Install](https://dortania.github.io/OpenCore-Post-Install/)
> [GPU Buyers Guide](https://dortania.github.io/GPU-Buyers-Guide/)
> [Wireless Buyers Guide](https://dortania.github.io/Wireless-Buyers-Guide/)
> [Anti Hackintosh Buyers Guide](https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/)

它们均来自 [Dortania](https://github.com/dortania/)。

其中的 [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide) 有我正在翻译的简体中文版本：
> [OpenCore 安装指南](https://thrrip.github.io/OpenCore-Install-Guide)

如果上方的网站在中国大陆地区打不开，可以尝试下方的反向代理地址：
> [OpenCore Install Guide](https://dortania-github-io.thrrip.space/OpenCore-Install-Guide)
> [OpenCore 安装指南](https://gh-pages.thrrip.space/OpenCore-Install-Guide)
> [Getting Started With ACPI](https://dortania-github-io.thrrip.space/Getting-Started-With-ACPI/)
> [OpenCore Post Install](https://dortania-github-io.thrrip.space/OpenCore-Post-Install/)
> [GPU Buyers Guide](https://dortania-github-io.thrrip.space/GPU-Buyers-Guide/)
> [Wireless Buyers Guide](https://dortania-github-io.thrrip.space/Wireless-Buyers-Guide/)
> [Anti Hackintosh Buyers Guide](https://dortania-github-io.thrrip.space/Anti-Hackintosh-Buyers-Guide/)

感谢您的支持！

**Comment by oreoft** [comment]
> 如果需要安装教程的话，可以参考 OpenCore 的官方文档，但其中除了配置 OpenCore 以外还包含了更多关于 Hackintosh 的内容：
> 
> > [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide)
> 
> 与其配套的还有：
> 
> > [Getting Started With ACPI](https://dortania.github.io/Getting-Started-With-ACPI/)
> > [OpenCore Post Install](https://dortania.github.io/OpenCore-Post-Install/)
> > [GPU Buyers Guide](https://dortania.github.io/GPU-Buyers-Guide/)
> > [Wireless Buyers Guide](https://dortania.github.io/Wireless-Buyers-Guide/)
> > [Anti Hackintosh Buyers Guide](https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/)
> 
> 它们均来自 [Dortania](https://github.com/dortania/)。
> 
> 其中的 [OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide) 有我正在翻译的简体中文版本：
> 
> > [OpenCore 安装指南](https://thrrip.github.io/OpenCore-Install-Guide)
> 
> 如果上方的网站在中国大陆地区打不开，可以尝试下方的反向代理地址：
> 
> > [OpenCore Install Guide](https://dortania-github-io.thrrip.space/OpenCore-Install-Guide)
> > [OpenCore 安装指南](https://gh-pages.thrrip.space/OpenCore-Install-Guide)
> > [Getting Started With ACPI](https://dortania-github-io.thrrip.space/Getting-Started-With-ACPI/)
> > [OpenCore Post Install](https://dortania-github-io.thrrip.space/OpenCore-Post-Install/)
> > [GPU Buyers Guide](https://dortania-github-io.thrrip.space/GPU-Buyers-Guide/)
> > [Wireless Buyers Guide](https://dortania-github-io.thrrip.space/Wireless-Buyers-Guide/)
> > [Anti Hackintosh Buyers Guide](https://dortania-github-io.thrrip.space/Anti-Hackintosh-Buyers-Guide/)
> 
> 感谢您的支持！

已经follow和star了，感谢你为c740黑苹果做出的共享，你好热心哦，哈哈哈
