### ISSUE TITLE
请问使用DW1820A网卡应该如何修改？

### ISSUE THREAD

**Issue by qpc001** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#8]

**Comment by ThrRip** [comment]
大半夜不睡觉来这里提Issue😂

说实话我也不太清楚，因为我没换网卡。

如果你的网卡是 DW1820A 的话，可以参考黑果小兵的这篇文章：[DW1820A/BCM94350ZAE/BCM94356ZEPA50DX插入的正确姿势](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html)

但是记得，需要先把我做好的 EFI 里面的 `AirportItlwm.kext`、`IntelBluetoothInjector.kext`、`IntelBluetoothFirmware.kext` 删除，`config.plist` 里面的对应信息也需要删除，然后再按照上面链接的文章进行操作。

感谢您对 ThrRip 的开源项目的支持，记得 Star & Follow 哦！

**Comment by qpc001** [comment]
是的，只需使用对应的kext 替换掉 原EFI中关于intel的kext，然后遵循 https://dortania.github.io/OpenCore-Install-Guide/config.plist/#creating-your-config-plist 来更新 config.plist即可完成驱动。 感谢。
