### ISSUE TITLE
连接显示器重启后，笔记本屏幕无法点亮

### ISSUE THREAD

**Issue by qpc001** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#9]
version 1.01

**Comment by ThrRip** [comment]
ThrRip 不会对此 Issue 进行任何技术性回复。

项目 [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML](/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML) 已经更新到 [Version 1.3.0](/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML/releases/tag/1.3.0)，之所以更新，就是因为存在问题，旧版本的问题或许已经在新版本中得到修复，所以请您尝试新版本的 EFI 文件后再决定是否提交 Issue。
